import sqlite3

def insert_player_stats_batch(players_data):
    """
    Function to insert player stats into player_stats table in Oxford_Utd_Stats.db database.

    Args:
    players_data (list): List of dictionaries, where each dictionary contains player stats to be inserted into the database.
    """
    conn = sqlite3.connect('Oxford_Utd_Stats.db')   # Connect to the database
    cursor = conn.cursor()  # Create cursor object

    for player_stats in players_data:   # Loop through each player stats dictionary
        stats_values = [
            player_stats.get("rating", None),
            player_stats.get("goals", None),
            player_stats.get("bigChancesCreated", None),
            player_stats.get("bigChancesMissed", None),
            player_stats.get("assists", None),
            player_stats.get("expectedAssists", None),
            player_stats.get("goalsAssistsSum", None),
            player_stats.get("accuratePasses", None),
            player_stats.get("inaccuratePasses", None),
            player_stats.get("totalPasses", None),
            player_stats.get("accuratePassesPercentage", None),
            player_stats.get("accurateOwnHalfPasses", None),
            player_stats.get("accurateOppositionHalfPasses", None),
            player_stats.get("accurateFinalThirdPasses", None),
            player_stats.get("keyPasses", None),
            player_stats.get("successfulDribbles", None),
            player_stats.get("successfulDribblesPercentage", None),
            player_stats.get("tackles", None),
            player_stats.get("interceptions", None),
            player_stats.get("yellowCards", None),
            player_stats.get("directRedCards", None),
            player_stats.get("redCards", None),
            player_stats.get("accurateCrosses", None),
            player_stats.get("accurateCrossesPercentage", None),
            player_stats.get("totalShots", None),
            player_stats.get("shotsOnTarget", None),
            player_stats.get("shotsOffTarget", None),
            player_stats.get("groundDuelsWon", None),
            player_stats.get("groundDuelsWonPercentage", None),
            player_stats.get("aerialDuelsWon", None),
            player_stats.get("aerialDuelsWonPercentage", None),
            player_stats.get("totalDuelsWon", None),
            player_stats.get("totalDuelsWonPercentage", None),
            player_stats.get("minutesPlayed", None),
            player_stats.get("goalConversionPercentage", None),
            player_stats.get("penaltiesTaken", None),
            player_stats.get("penaltyGoals", None),
            player_stats.get("penaltyWon", None),
            player_stats.get("penaltyConceded", None),
            player_stats.get("shotFromSetPiece", None),
            player_stats.get("freeKickGoal", None),
            player_stats.get("goalsFromInsideTheBox", None),
            player_stats.get("goalsFromOutsideTheBox", None),
            player_stats.get("shotsFromInsideTheBox", None),
            player_stats.get("shotsFromOutsideTheBox", None),
            player_stats.get("headedGoals", None),
            player_stats.get("leftFootGoals", None),
            player_stats.get("rightFootGoals", None),
            player_stats.get("accurateLongBalls", None),
            player_stats.get("accurateLongBallsPercentage", None),
            player_stats.get("clearances", None),
            player_stats.get("errorLeadToGoal", None),
            player_stats.get("errorLeadToShot", None),
            player_stats.get("dispossessed", None),
            player_stats.get("possessionLost", None),
            player_stats.get("possessionWonAttThird", None),
            player_stats.get("totalChippedPasses", None),
            player_stats.get("accurateChippedPasses", None),
            player_stats.get("touches", None),
            player_stats.get("wasFouled", None),
            player_stats.get("fouls", None),
            player_stats.get("hitWoodwork", None),
            player_stats.get("ownGoals", None),
            player_stats.get("dribbledPast", None),
            player_stats.get("offsides", None),
            player_stats.get("blockedShots", None),
            player_stats.get("passToAssist", None),
            player_stats.get("saves", None),
            player_stats.get("cleanSheet", None),
            player_stats.get("penaltyFaced", None),
            player_stats.get("penaltySave", None),
            player_stats.get("savedShotsFromInsideTheBox", None),
            player_stats.get("savedShotsFromOutsideTheBox", None),
            player_stats.get("goalsConcededInsideTheBox", None),
            player_stats.get("goalsConcededOutsideTheBox", None),
            player_stats.get("punches", None),
            player_stats.get("runsOut", None),
            player_stats.get("successfulRunsOut", None),
            player_stats.get("highClaims", None),
            player_stats.get("crossesNotClaimed", None),
            player_stats.get("matchesStarted", None),
            player_stats.get("penaltyConversion", None),
            player_stats.get("setPieceConversion", None),
            player_stats.get("totalAttemptAssist", None),
            player_stats.get("totalContest", None),
            player_stats.get("totalCross", None),
            player_stats.get("duelLost", None),
            player_stats.get("aerialLost", None),
            player_stats.get("attemptPenaltyMiss", None),
            player_stats.get("attemptPenaltyPost", None),
            player_stats.get("attemptPenaltyTarget", None),
            player_stats.get("totalLongBalls", None),
            player_stats.get("goalsConceded", None),
            player_stats.get("tacklesWon", None),
            player_stats.get("tacklesWonPercentage", None),
            player_stats.get("scoringFrequency", None),
            player_stats.get("yellowRedCards", None),
            player_stats.get("savesCaught", None),
            player_stats.get("savesParried", None),
            player_stats.get("totalOwnHalfPasses", None),
            player_stats.get("totalOppositionHalfPasses", None),
            player_stats.get("totwAppearances", None),
            player_stats.get("expectedGoals", None),
            player_stats.get("goalKicks", None),
            player_stats.get("ballRecovery", None),
            player_stats.get("appearances", None)
        ]

        stats_values = [player_stats.get("Name", None), player_stats.get("Position", None)] + stats_values  # Add player name and position to the stats_values list

        # Insert player stats into player_stats table
        cursor.execute('''  
        INSERT OR REPLACE INTO player_stats (
            Name, Position, rating, goals, bigChancesCreated, bigChancesMissed, assists, expectedAssists,
            goalsAssistsSum, accuratePasses, inaccuratePasses, totalPasses, accuratePassesPercentage,
            accurateOwnHalfPasses, accurateOppositionHalfPasses, accurateFinalThirdPasses, keyPasses,
            successfulDribbles, successfulDribblesPercentage, tackles, interceptions, yellowCards,
            directRedCards, redCards, accurateCrosses, accurateCrossesPercentage, totalShots, shotsOnTarget,
            shotsOffTarget, groundDuelsWon, groundDuelsWonPercentage, aerialDuelsWon, aerialDuelsWonPercentage,
            totalDuelsWon, totalDuelsWonPercentage, minutesPlayed, goalConversionPercentage, penaltiesTaken,
            penaltyGoals, penaltyWon, penaltyConceded, shotFromSetPiece, freeKickGoal, goalsFromInsideTheBox,
            goalsFromOutsideTheBox, shotsFromInsideTheBox, shotsFromOutsideTheBox, headedGoals, leftFootGoals,
            rightFootGoals, accurateLongBalls, accurateLongBallsPercentage, clearances, errorLeadToGoal,
            errorLeadToShot, dispossessed, possessionLost, possessionWonAttThird, totalChippedPasses,
            accurateChippedPasses, touches, wasFouled, fouls, hitWoodwork, ownGoals, dribbledPast, offsides,
            blockedShots, passToAssist, saves, cleanSheet, penaltyFaced, penaltySave, savedShotsFromInsideTheBox,
            savedShotsFromOutsideTheBox, goalsConcededInsideTheBox, goalsConcededOutsideTheBox, punches,
            runsOut, successfulRunsOut, highClaims, crossesNotClaimed, matchesStarted, penaltyConversion,
            setPieceConversion, totalAttemptAssist, totalContest, totalCross, duelLost, aerialLost,
            attemptPenaltyMiss, attemptPenaltyPost, attemptPenaltyTarget, totalLongBalls, goalsConceded,
            tacklesWon, tacklesWonPercentage, scoringFrequency, yellowRedCards, savesCaught, savesParried,
            totalOwnHalfPasses, totalOppositionHalfPasses, totwAppearances, expectedGoals, goalKicks,
            ballRecovery, appearances
    )
    VALUES (
        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
    )
    ''', stats_values)  # Execute the insert query

    # Commit changes and close connection
    conn.commit()
    conn.close()

# List of dictionaries containing player stats to be inserted into the database
players_data = [
    {
    "Name": "Mark Harris", "Position": "CF", "rating": 6.628, "goals": 5, "bigChancesCreated": 0,
    "bigChancesMissed": 8, "assists": 0, "expectedAssists": 0.25519863, "goalsAssistsSum": 5, 
    "accuratePasses": 188, "inaccuratePasses": 59, "totalPasses": 247, "accuratePassesPercentage": 76.113360323887,
    "accurateOwnHalfPasses": 69, "accurateOppositionHalfPasses": 119, "accurateFinalThirdPasses": 68, 
    "keyPasses": 14, "successfulDribbles": 11, "successfulDribblesPercentage": 47.826086956522, 
    "tackles": 11, "interceptions": 1, "yellowCards": 2, "directRedCards": 0, "redCards": 0, "accurateCrosses": 0,
    "accurateCrossesPercentage": 0, "totalShots": 28, "shotsOnTarget": 15, "shotsOffTarget": 8, 
    "groundDuelsWon": 40, "groundDuelsWonPercentage": 37.383177570093, "aerialDuelsWon": 9, 
    "aerialDuelsWonPercentage": 23.076923076923, "totalDuelsWon": 49, "totalDuelsWonPercentage": 33.561643835616,
    "minutesPlayed": 1599, "goalConversionPercentage": 17.857142857143, "penaltiesTaken": 0, "penaltyGoals": 0,
    "penaltyWon": 0, "penaltyConceded": 1, "shotFromSetPiece": 0, "freeKickGoal": 0, "goalsFromInsideTheBox": 4,
    "goalsFromOutsideTheBox": 1, "shotsFromInsideTheBox": 17, "shotsFromOutsideTheBox": 11, "headedGoals": 1,
    "leftFootGoals": 1, "rightFootGoals": 2, "accurateLongBalls": 5, "accurateLongBallsPercentage": 50,
    "clearances": 10, "errorLeadToGoal": 0, "errorLeadToShot": 0, "dispossessed": 21, "possessionLost": 148,
    "possessionWonAttThird": 8, "totalChippedPasses": 5, "accurateChippedPasses": 0, "touches": 450, "wasFouled": 18,
    "fouls": 29, "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 7, "offsides": 19, "blockedShots": 5,
    "passToAssist": 0, "saves": 0, "cleanSheet": 1, "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0,
    "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 24, "goalsConcededOutsideTheBox": 2,
    "punches": 0, "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 19,
    "penaltyConversion": 0, "setPieceConversion": 0, "totalAttemptAssist": 14, "totalContest": 23, "totalCross": 0,
    "duelLost": 97, "aerialLost": 30, "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0,
    "totalLongBalls": 10, "goalsConceded": 26, "tacklesWon": 9, "tacklesWonPercentage": 81.818181818182,
    "scoringFrequency": 319.8, "yellowRedCards": 0, "savesCaught": 0, "savesParried": 0, "totalOwnHalfPasses": 89,
    "totalOppositionHalfPasses": 158, "totwAppearances": 0, "expectedGoals": 6.0934, "goalKicks": 0,
    "ballRecovery": 38, "appearances": 25
    },
    {
    "Name": "Dane Scarlett", "Position": "CF", "rating": 6.5722222222222, "goals": 4, "bigChancesCreated": 0,
    "bigChancesMissed": 1, "assists": 0, "expectedAssists": 0.46628536, "goalsAssistsSum": 4, "accuratePasses": 67,
    "inaccuratePasses": 39, "totalPasses": 106, "accuratePassesPercentage": 63.207547169811, "accurateOwnHalfPasses": 22,
    "accurateOppositionHalfPasses": 46, "accurateFinalThirdPasses": 21, "keyPasses": 4, "successfulDribbles": 8,
    "successfulDribblesPercentage": 38.095238095238, "tackles": 3, "interceptions": 6, "yellowCards": 1,
    "directRedCards": 0, "redCards": 0, "accurateCrosses": 1, "accurateCrossesPercentage": 50, "totalShots": 12,
    "shotsOnTarget": 7, "shotsOffTarget": 2, "groundDuelsWon": 26, "groundDuelsWonPercentage": 34.666666666667,
    "aerialDuelsWon": 15, "aerialDuelsWonPercentage": 20.27027027027, "totalDuelsWon": 41, "totalDuelsWonPercentage": 27.51677852349,
    "minutesPlayed": 783, "goalConversionPercentage": 33.333333333333, "penaltiesTaken": 0, "penaltyGoals": 0,
    "penaltyWon": 0, "penaltyConceded": 0, "shotFromSetPiece": 1, "freeKickGoal": 0, "goalsFromInsideTheBox": 4,
    "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 7, "shotsFromOutsideTheBox": 5, "headedGoals": 1,
    "leftFootGoals": 2, "rightFootGoals": 1, "accurateLongBalls": 4, "accurateLongBallsPercentage": 44.444444444444,
    "clearances": 8, "errorLeadToGoal": 0, "errorLeadToShot": 0, "dispossessed": 18, "possessionLost": 109,
    "possessionWonAttThird": 3, "totalChippedPasses": 1, "accurateChippedPasses": 0, "touches": 250, "wasFouled": 15,
    "fouls": 16, "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 5, "offsides": 11, "blockedShots": 3,
    "passToAssist": 0, "saves": 0, "cleanSheet": 0, "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0,
    "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 14, "goalsConcededOutsideTheBox": 3,
    "punches": 0, "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 7,
    "penaltyConversion": 0, "setPieceConversion": 0, "totalAttemptAssist": 4, "totalContest": 21, "totalCross": 2,
    "duelLost": 108, "aerialLost": 59, "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0,
    "totalLongBalls": 9, "goalsConceded": 17, "tacklesWon": 0, "tacklesWonPercentage": 0, "scoringFrequency": 195.75,
    "yellowRedCards": 0, "savesCaught": 0, "savesParried": 0, "totalOwnHalfPasses": 33, "totalOppositionHalfPasses": 75,
    "totwAppearances": 0, "expectedGoals": 0.8311, "goalKicks": 0, "ballRecovery": 21, "appearances": 19
    },
   {
    "Name": "Will Goodwin", "Position": "CF", "rating": 6.6, "goals": 0, "bigChancesCreated": 1, "bigChancesMissed": 0, "assists": 0,
    "goalsAssistsSum": 0, "accuratePasses": 2, "inaccuratePasses": 3, "totalPasses": 5, "accuratePassesPercentage": 40, "accurateOwnHalfPasses": 0,
    "accurateOppositionHalfPasses": 2, "accurateFinalThirdPasses": 2, "keyPasses": 1, "successfulDribbles": 0, "successfulDribblesPercentage": 0,
    "tackles": 0, "interceptions": 0, "yellowCards": 0, "directRedCards": 0, "redCards": 0, "accurateCrosses": 0, "accurateCrossesPercentage": 0,
    "totalShots": 0, "shotsOnTarget": 0, "shotsOffTarget": 0, "groundDuelsWon": 1, "groundDuelsWonPercentage": 50, "aerialDuelsWon": 1,
    "aerialDuelsWonPercentage": 50, "totalDuelsWon": 2, "totalDuelsWonPercentage": 50, "minutesPlayed": 35, "goalConversionPercentage": 0, "penaltiesTaken": 0,
    "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 0, "shotFromSetPiece": 0, "freeKickGoal": 0, "goalsFromInsideTheBox": 0,
    "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 0, "shotsFromOutsideTheBox": 0, "headedGoals": 0, "leftFootGoals": 0, "rightFootGoals": 0,
    "accurateLongBalls": 0, "accurateLongBallsPercentage": 0, "clearances": 0, "errorLeadToGoal": 0, "errorLeadToShot": 0, "dispossessed": 0,
    "possessionLost": 4, "possessionWonAttThird": 0, "totalChippedPasses": 0, "accurateChippedPasses": 0, "touches": 7, "wasFouled": 1, "fouls": 0,
    "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 0, "offsides": 0, "blockedShots": 0, "passToAssist": 0, "saves": 0, "cleanSheet": 0, "penaltyFaced": 0,
    "penaltySave": 0, "savedShotsFromInsideTheBox": 0, "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 0, "goalsConcededOutsideTheBox": 0,
    "punches": 0, "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 0, "penaltyConversion": 0,
    "setPieceConversion": 0, "totalAttemptAssist": 1, "totalContest": 1, "totalCross": 0, "duelLost": 2, "aerialLost": 1, "attemptPenaltyMiss": 0,
    "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0, "totalLongBalls": 0, "goalsConceded": 0, "tacklesWon": 0, "tacklesWonPercentage": 0, "scoringFrequency": 0,
    "yellowRedCards": 0, "savesCaught": 0, "savesParried": 0, "totalOwnHalfPasses": 0, "totalOppositionHalfPasses": 5, "totwAppearances": 0, "expectedGoals": 0, 
    "goalKicks": 0, "ballRecovery": 0, "appearances": 3
    },
    {
    "Name": "Marselino Ferdinan", "Position": "AM", "rating": 6.8333333333333, "goals": 0, "bigChancesCreated": 0,
    "bigChancesMissed": 0, "assists": 0, "goalsAssistsSum": 0, "accuratePasses": 76, "inaccuratePasses": 16,
    "totalPasses": 92, "accuratePassesPercentage": 82.608695652174, "accurateOwnHalfPasses": 29,
    "accurateOppositionHalfPasses": 48, "accurateFinalThirdPasses": 25, "keyPasses": 4, "successfulDribbles": 4,
    "successfulDribblesPercentage": 50, "tackles": 6, "interceptions": 2, "yellowCards": 0, "directRedCards": 0,
    "redCards": 1, "accurateCrosses": 1, "accurateCrossesPercentage": 25, "totalShots": 11, "shotsOnTarget": 4,
    "shotsOffTarget": 3, "groundDuelsWon": 16, "groundDuelsWonPercentage": 44.444444444444, "aerialDuelsWon": 0,
    "aerialDuelsWonPercentage": 0, "totalDuelsWon": 16, "totalDuelsWonPercentage": 42.105263157895, "minutesPlayed": 236,
    "goalConversionPercentage": 0, "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 0,
    "shotFromSetPiece": 3, "freeKickGoal": 0, "goalsFromInsideTheBox": 0, "goalsFromOutsideTheBox": 0,
    "shotsFromInsideTheBox": 5, "shotsFromOutsideTheBox": 6, "headedGoals": 0, "leftFootGoals": 0, "rightFootGoals": 0,
    "accurateLongBalls": 5, "accurateLongBallsPercentage": 41.666666666667, "clearances": 0, "errorLeadToGoal": 0,
    "errorLeadToShot": 0, "dispossessed": 6, "possessionLost": 46, "possessionWonAttThird": 5, "totalChippedPasses": 9,
    "accurateChippedPasses": 5, "touches": 160, "wasFouled": 6, "fouls": 5, "hitWoodwork": 1, "ownGoals": 0,
    "dribbledPast": 5, "offsides": 0, "blockedShots": 4, "passToAssist": 0, "saves": 0, "cleanSheet": 0, "penaltyFaced": 0,
    "penaltySave": 0, "savedShotsFromInsideTheBox": 0, "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 3,
    "goalsConcededOutsideTheBox": 0, "punches": 0, "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0,
    "crossesNotClaimed": 0, "matchesStarted": 3, "penaltyConversion": 0, "setPieceConversion": 0,
    "totalAttemptAssist": 4, "totalContest": 8, "totalCross": 4, "duelLost": 22, "aerialLost": 2, "attemptPenaltyMiss": 0,
    "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0, "totalLongBalls": 12, "goalsConceded": 3, "tacklesWon": 5,
    "tacklesWonPercentage": 83.333333333333, "scoringFrequency": 0, "yellowRedCards": 1, "savesCaught": 0,
    "savesParried": 0, "totalOwnHalfPasses": 30, "totalOppositionHalfPasses": 66, "totwAppearances": 0,
    "expectedGoals": 0.8311, "goalKicks": 0, "ballRecovery": 12, "appearances": 3
    },
    {
    "Name": "Przemysław Płacheta", "Position": "LW", "rating": 6.6090909090909, "goals": 2, "bigChancesCreated": 3,
    "bigChancesMissed": 1, "assists": 2, "goalsAssistsSum": 4, "accuratePasses": 127, "inaccuratePasses": 42,
    "totalPasses": 169, "accuratePassesPercentage": 75.147928994083, "accurateOwnHalfPasses": 48,
    "accurateOppositionHalfPasses": 82, "accurateFinalThirdPasses": 42, "keyPasses": 7, "successfulDribbles": 4,
    "successfulDribblesPercentage": 22.222222222222, "tackles": 9, "interceptions": 3, "yellowCards": 0, "directRedCards": 0,
    "redCards": 0, "accurateCrosses": 3, "accurateCrossesPercentage": 15, "totalShots": 13, "shotsOnTarget": 4,
    "shotsOffTarget": 5, "groundDuelsWon": 19, "groundDuelsWonPercentage": 25.675675675676, "aerialDuelsWon": 7,
    "aerialDuelsWonPercentage": 38.888888888889, "totalDuelsWon": 26, "totalDuelsWonPercentage": 28.260869565217,
    "minutesPlayed": 657, "goalConversionPercentage": 15.384615384615, "penaltiesTaken": 0, "penaltyGoals": 0,
    "penaltyWon": 0, "penaltyConceded": 0, "shotFromSetPiece": 0, "freeKickGoal": 0, "goalsFromInsideTheBox": 1,
    "goalsFromOutsideTheBox": 1, "shotsFromInsideTheBox": 9, "shotsFromOutsideTheBox": 4, "headedGoals": 0,
    "leftFootGoals": 2, "rightFootGoals": 0, "accurateLongBalls": 2, "accurateLongBallsPercentage": 22.222222222222,
    "clearances": 6, "errorLeadToGoal": 0, "errorLeadToShot": 0, "dispossessed": 16, "possessionLost": 114,
    "possessionWonAttThird": 1, "totalChippedPasses": 8, "accurateChippedPasses": 3, "touches": 311, "wasFouled": 7,
    "fouls": 10, "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 15, "offsides": 0, "blockedShots": 4,
    "passToAssist": 0, "saves": 0, "cleanSheet": 0, "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0,
    "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 10, "goalsConcededOutsideTheBox": 2, "punches": 0,
    "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 9,
    "penaltyConversion": 0, "setPieceConversion": 0, "totalAttemptAssist": 7, "totalContest": 18, "totalCross": 20,
    "duelLost": 66, "aerialLost": 11, "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0,
    "totalLongBalls": 9, "goalsConceded": 12, "tacklesWon": 7, "tacklesWonPercentage": 77.777777777778,
    "scoringFrequency": 328.5, "yellowRedCards": 0, "savesCaught": 0, "savesParried": 0, "totalOwnHalfPasses": 61,
    "totalOppositionHalfPasses": 128, "totwAppearances": 0, "expectedGoals": 1.3751, "goalKicks": 0, "ballRecovery": 31,
    "appearances": 11
    },
    {
    "Name": "Malcolm Ebiowei", "Position": "RW", "rating": 6.625, "goals": 0, "bigChancesCreated": 0,
    "bigChancesMissed": 0, "assists": 0, "goalsAssistsSum": 0, "accuratePasses": 9, "inaccuratePasses": 4,
    "totalPasses": 13, "accuratePassesPercentage": 69.230769230769, "accurateOwnHalfPasses": 1,
    "accurateOppositionHalfPasses": 9, "accurateFinalThirdPasses": 5, "keyPasses": 1, "successfulDribbles": 0,
    "successfulDribblesPercentage": 0, "tackles": 3, "interceptions": 1, "yellowCards": 1, "directRedCards": 0,
    "redCards": 0, "accurateCrosses": 1, "accurateCrossesPercentage": 33.333333333333, "totalShots": 3,
    "shotsOnTarget": 2, "shotsOffTarget": 1, "groundDuelsWon": 4, "groundDuelsWonPercentage": 30.769230769231,
    "aerialDuelsWon": 0, "aerialDuelsWonPercentage": 0, "totalDuelsWon": 4, "totalDuelsWonPercentage": 26.666666666667,
    "minutesPlayed": 64, "goalConversionPercentage": 0, "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0,
    "penaltyConceded": 0, "shotFromSetPiece": 0, "freeKickGoal": 0, "goalsFromInsideTheBox": 0,
    "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 3, "shotsFromOutsideTheBox": 0, "headedGoals": 0,
    "leftFootGoals": 0, "rightFootGoals": 0, "accurateLongBalls": 0, "accurateLongBallsPercentage": 0,
    "clearances": 0, "errorLeadToGoal": 0, "errorLeadToShot": 0, "dispossessed": 3, "possessionLost": 18,
    "possessionWonAttThird": 0, "totalChippedPasses": 3, "accurateChippedPasses": 0, "touches": 40, "wasFouled": 1,
    "fouls": 2, "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 0, "offsides": 1, "blockedShots": 0,
    "passToAssist": 0, "saves": 0, "cleanSheet": 0, "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0,
    "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 1, "goalsConcededOutsideTheBox": 0, "punches": 0,
    "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 0,
    "penaltyConversion": 0, "setPieceConversion": 0, "totalAttemptAssist": 1, "totalContest": 4, "totalCross": 3,
    "duelLost": 11, "aerialLost": 2, "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0,
    "totalLongBalls": 2, "goalsConceded": 1, "tacklesWon": 2, "tacklesWonPercentage": 66.666666666667, "scoringFrequency": 0,
    "yellowRedCards": 0, "savesCaught": 0, "savesParried": 0, "totalOwnHalfPasses": 1, "totalOppositionHalfPasses": 15,
    "totwAppearances": 0, "expectedGoals": 0.2241, "goalKicks": 0, "ballRecovery": 3, "appearances": 4
    },
    {
    "Name": "Siriki Dembélé", "Position": "LW", "rating": 6.63, "goals": 0, "bigChancesCreated": 1,
    "bigChancesMissed": 0, "assists": 1, "goalsAssistsSum": 1, "accuratePasses": 88, "inaccuratePasses": 22,
    "totalPasses": 110, "accuratePassesPercentage": 80, "accurateOwnHalfPasses": 28, "accurateOppositionHalfPasses": 60,
    "accurateFinalThirdPasses": 36, "keyPasses": 2, "successfulDribbles": 7, "successfulDribblesPercentage": 29.166666666667,
    "tackles": 12, "interceptions": 4, "yellowCards": 2, "directRedCards": 0, "redCards": 0, "accurateCrosses": 0,
    "accurateCrossesPercentage": 0, "totalShots": 12, "shotsOnTarget": 0, "shotsOffTarget": 5, "groundDuelsWon": 34,
    "groundDuelsWonPercentage": 47.887323943662, "aerialDuelsWon": 2, "aerialDuelsWonPercentage": 20,
    "totalDuelsWon": 36, "totalDuelsWonPercentage": 44.444444444444, "minutesPlayed": 484, "goalConversionPercentage": 0,
    "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 0, "shotFromSetPiece": 1,
    "freeKickGoal": 0, "goalsFromInsideTheBox": 0, "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 7,
    "shotsFromOutsideTheBox": 5, "headedGoals": 0, "leftFootGoals": 0, "rightFootGoals": 0, "accurateLongBalls": 3,
    "accurateLongBallsPercentage": 75, "clearances": 1, "errorLeadToGoal": 0, "errorLeadToShot": 0, "dispossessed": 13,
    "possessionLost": 82, "possessionWonAttThird": 1, "totalChippedPasses": 3, "accurateChippedPasses": 3, "touches": 246,
    "wasFouled": 15, "fouls": 6, "hitWoodwork": 1, "ownGoals": 0, "dribbledPast": 3, "offsides": 3, "blockedShots": 7,
    "passToAssist": 0, "saves": 0, "cleanSheet": 0, "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0,
    "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 4, "goalsConcededOutsideTheBox": 1, "punches": 0,
    "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 5, "penaltyConversion": 0,
    "setPieceConversion": 0, "totalAttemptAssist": 2, "totalContest": 24, "totalCross": 9, "duelLost": 45, "aerialLost": 8,
    "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0, "totalLongBalls": 4, "goalsConceded": 5,
    "tacklesWon": 6, "tacklesWonPercentage": 50, "scoringFrequency": 0, "yellowRedCards": 0, "savesCaught": 0,
    "savesParried": 0, "totalOwnHalfPasses": 33, "totalOppositionHalfPasses": 86, "totwAppearances": 0, "expectedGoals": 0.7617,
    "goalKicks": 0, "ballRecovery": 27, "appearances": 10
    },
    {
    "Name": "Cameron Brannagan", "Position": "CM", "rating": 7.0571428571429, "goals": 1, "bigChancesCreated": 1,
    "bigChancesMissed": 0, "assists": 2, "goalsAssistsSum": 3, "accuratePasses": 476, "inaccuratePasses": 70,
    "totalPasses": 546, "accuratePassesPercentage": 87.179487179487, "accurateOwnHalfPasses": 292,
    "accurateOppositionHalfPasses": 187, "accurateFinalThirdPasses": 102, "keyPasses": 10, "successfulDribbles": 1,
    "successfulDribblesPercentage": 50, "tackles": 27, "interceptions": 15, "yellowCards": 2, "directRedCards": 0,
    "redCards": 0, "accurateCrosses": 3, "accurateCrossesPercentage": 33.333333333333, "totalShots": 17,
    "shotsOnTarget": 7, "shotsOffTarget": 5, "groundDuelsWon": 43, "groundDuelsWonPercentage": 58.904109589041,
    "aerialDuelsWon": 0, "aerialDuelsWonPercentage": 0, "totalDuelsWon": 43, "totalDuelsWonPercentage": 55.128205128205,
    "minutesPlayed": 1197, "goalConversionPercentage": 5.8823529411765, "penaltiesTaken": 0, "penaltyGoals": 0,
    "penaltyWon": 0, "penaltyConceded": 0, "shotFromSetPiece": 0, "freeKickGoal": 0, "goalsFromInsideTheBox": 1,
    "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 3, "shotsFromOutsideTheBox": 14, "headedGoals": 0,
    "leftFootGoals": 0, "rightFootGoals": 1, "accurateLongBalls": 41, "accurateLongBallsPercentage": 56.944444444444,
    "clearances": 15, "errorLeadToGoal": 0, "errorLeadToShot": 0, "dispossessed": 2, "possessionLost": 90,
    "possessionWonAttThird": 3, "totalChippedPasses": 58, "accurateChippedPasses": 31, "touches": 706, "wasFouled": 15,
    "fouls": 13, "hitWoodwork": 2, "ownGoals": 0, "dribbledPast": 14, "offsides": 0, "blockedShots": 5, "passToAssist": 2,
    "saves": 0, "cleanSheet": 3, "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0,
    "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 22, "goalsConcededOutsideTheBox": 2, "punches": 0,
    "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 14,
    "penaltyConversion": 0, "setPieceConversion": 0, "totalAttemptAssist": 8, "totalContest": 2, "totalCross": 9,
    "duelLost": 35, "aerialLost": 5, "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0,
    "totalLongBalls": 72, "goalsConceded": 24, "tacklesWon": 17, "tacklesWonPercentage": 62.962962962963,
    "scoringFrequency": 1197, "yellowRedCards": 0, "savesCaught": 0, "savesParried": 0, "totalOwnHalfPasses": 311,
    "totalOppositionHalfPasses": 244, "totwAppearances": 1, "expectedGoals": 0.4741, "goalKicks": 0, "ballRecovery": 53,
    "appearances": 14
    },
    {
    "Name": "Louie Sibley", "Position": "CM", "rating": 6.575, "goals": 1, "bigChancesCreated": 0, "bigChancesMissed": 0,
    "assists": 0, "goalsAssistsSum": 1, "accuratePasses": 29, "inaccuratePasses": 6, "totalPasses": 35,
    "accuratePassesPercentage": 82.857142857143, "accurateOwnHalfPasses": 15, "accurateOppositionHalfPasses": 14,
    "accurateFinalThirdPasses": 9, "keyPasses": 1, "successfulDribbles": 2, "successfulDribblesPercentage": 40,
    "tackles": 5, "interceptions": 0, "yellowCards": 3, "directRedCards": 0, "redCards": 0, "accurateCrosses": 0,
    "accurateCrossesPercentage": 0, "totalShots": 5, "shotsOnTarget": 2, "shotsOffTarget": 1, "groundDuelsWon": 10,
    "groundDuelsWonPercentage": 41.666666666667, "aerialDuelsWon": 0, "aerialDuelsWonPercentage": 0, "totalDuelsWon": 10,
    "totalDuelsWonPercentage": 37.037037037037, "minutesPlayed": 163, "goalConversionPercentage": 20, "penaltiesTaken": 0,
    "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 0, "shotFromSetPiece": 0, "freeKickGoal": 0,
    "goalsFromInsideTheBox": 0, "goalsFromOutsideTheBox": 1, "shotsFromInsideTheBox": 3, "shotsFromOutsideTheBox": 2,
    "headedGoals": 0, "leftFootGoals": 1, "rightFootGoals": 0, "accurateLongBalls": 4, "accurateLongBallsPercentage": 57.142857142857,
    "clearances": 5, "errorLeadToGoal": 0, "errorLeadToShot": 0, "dispossessed": 3, "possessionLost": 22,
    "possessionWonAttThird": 0, "totalChippedPasses": 2, "accurateChippedPasses": 0, "touches": 78, "wasFouled": 3,
    "fouls": 4, "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 4, "offsides": 0, "blockedShots": 2, "passToAssist": 0,
    "saves": 0, "cleanSheet": 0, "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0,
    "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 4, "goalsConcededOutsideTheBox": 0, "punches": 0,
    "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 1,
    "penaltyConversion": 0, "setPieceConversion": 0, "totalAttemptAssist": 1, "totalContest": 5, "totalCross": 3,
    "duelLost": 17, "aerialLost": 3, "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0,
    "totalLongBalls": 7, "goalsConceded": 4, "tacklesWon": 1, "tacklesWonPercentage": 20, "scoringFrequency": 163,
    "yellowRedCards": 0, "savesCaught": 0, "savesParried": 0, "totalOwnHalfPasses": 16, "totalOppositionHalfPasses": 22,
    "totwAppearances": 0, "expectedGoals": 0.2016, "goalKicks": 0, "ballRecovery": 9, "appearances": 10
    },
    {
    "Name": "Tyler Goodrham", "Position": "RW", "rating": 6.76, "goals": 3, "bigChancesCreated": 1, "bigChancesMissed": 2,
    "assists": 3, "goalsAssistsSum": 6, "accuratePasses": 531, "inaccuratePasses": 151, "totalPasses": 682,
    "accuratePassesPercentage": 77.859237536657, "accurateOwnHalfPasses": 230, "accurateOppositionHalfPasses": 328,
    "accurateFinalThirdPasses": 159, "keyPasses": 34, "successfulDribbles": 31, "successfulDribblesPercentage": 36.046511627907,
    "tackles": 41, "interceptions": 15, "yellowCards": 4, "directRedCards": 0, "redCards": 0, "accurateCrosses": 27,
    "accurateCrossesPercentage": 43.548387096774, "totalShots": 34, "shotsOnTarget": 11, "shotsOffTarget": 11,
    "groundDuelsWon": 102, "groundDuelsWonPercentage": 40.8, "aerialDuelsWon": 16, "aerialDuelsWonPercentage": 26.666666666667,
    "totalDuelsWon": 118, "totalDuelsWonPercentage": 38.064516129032, "minutesPlayed": 2184, "goalConversionPercentage": 8.8235294117647,
    "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 0, "shotFromSetPiece": 0, "freeKickGoal": 0,
    "goalsFromInsideTheBox": 1, "goalsFromOutsideTheBox": 2, "shotsFromInsideTheBox": 11, "shotsFromOutsideTheBox": 23,
    "headedGoals": 0, "leftFootGoals": 2, "rightFootGoals": 1, "accurateLongBalls": 27, "accurateLongBallsPercentage": 41.538461538462,
    "clearances": 33, "errorLeadToGoal": 0, "errorLeadToShot": 0, "dispossessed": 34, "possessionLost": 342, "possessionWonAttThird": 15,
    "totalChippedPasses": 48, "accurateChippedPasses": 22, "touches": 1182, "wasFouled": 31, "fouls": 34, "hitWoodwork": 0,
    "ownGoals": 0, "dribbledPast": 25, "offsides": 4, "blockedShots": 12, "passToAssist": 0, "saves": 0, "cleanSheet": 4,
    "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0, "savedShotsFromOutsideTheBox": 0,
    "goalsConcededInsideTheBox": 33, "goalsConcededOutsideTheBox": 5, "punches": 0, "runsOut": 0, "successfulRunsOut": 0,
    "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 25, "penaltyConversion": 0, "setPieceConversion": 0,
    "totalAttemptAssist": 34, "totalContest": 86, "totalCross": 62, "duelLost": 192, "aerialLost": 44, "attemptPenaltyMiss": 0,
    "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0, "totalLongBalls": 65, "goalsConceded": 38, "tacklesWon": 26,
    "tacklesWonPercentage": 63.414634146341, "scoringFrequency": 728, "yellowRedCards": 0, "savesCaught": 0,
    "savesParried": 0, "totalOwnHalfPasses": 267, "totalOppositionHalfPasses": 477, "totwAppearances": 0, "expectedGoals": 1.6412,
    "goalKicks": 0, "ballRecovery": 103, "appearances": 25
    },
    {
    "Name": "Rúben Rodrigues", "Position": "AM", "rating": 6.86, "goals": 4, "bigChancesCreated": 6, "bigChancesMissed": 4,
    "assists": 3, "goalsAssistsSum": 7, "accuratePasses": 343, "inaccuratePasses": 109, "totalPasses": 452,
    "accuratePassesPercentage": 75.884955752212, "accurateOwnHalfPasses": 159, "accurateOppositionHalfPasses": 185,
    "accurateFinalThirdPasses": 108, "keyPasses": 21, "successfulDribbles": 12, "successfulDribblesPercentage": 37.5,
    "tackles": 31, "interceptions": 15, "yellowCards": 2, "directRedCards": 0, "redCards": 0, "accurateCrosses": 1,
    "accurateCrossesPercentage": 12.5, "totalShots": 24, "shotsOnTarget": 8, "shotsOffTarget": 12, "groundDuelsWon": 79,
    "groundDuelsWonPercentage": 53.378378378378, "aerialDuelsWon": 19, "aerialDuelsWonPercentage": 38.775510204082,
    "totalDuelsWon": 98, "totalDuelsWonPercentage": 49.746192893401, "minutesPlayed": 1581, "goalConversionPercentage": 16.666666666667,
    "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 0, "shotFromSetPiece": 0, "freeKickGoal": 0,
    "goalsFromInsideTheBox": 4, "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 22, "shotsFromOutsideTheBox": 2,
    "headedGoals": 1, "leftFootGoals": 0, "rightFootGoals": 3, "accurateLongBalls": 15, "accurateLongBallsPercentage": 55.555555555556,
    "clearances": 14, "errorLeadToGoal": 1, "errorLeadToShot": 1, "dispossessed": 24, "possessionLost": 205,
    "possessionWonAttThird": 11, "totalChippedPasses": 30, "accurateChippedPasses": 15, "touches": 748, "wasFouled": 36,
    "fouls": 13, "hitWoodwork": 1, "ownGoals": 0, "dribbledPast": 12, "offsides": 3, "blockedShots": 4, "passToAssist": 0,
    "saves": 0, "cleanSheet": 0, "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0, "savedShotsFromOutsideTheBox": 0,
    "goalsConcededInsideTheBox": 25, "goalsConcededOutsideTheBox": 3, "punches": 0, "runsOut": 0, "successfulRunsOut": 0,
    "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 20, "penaltyConversion": 0, "setPieceConversion": 0,
    "totalAttemptAssist": 21, "totalContest": 32, "totalCross": 8, "duelLost": 99, "aerialLost": 30, "attemptPenaltyMiss": 0,
    "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0, "totalLongBalls": 27, "goalsConceded": 28, "tacklesWon": 16,
    "tacklesWonPercentage": 51.612903225806, "scoringFrequency": 395.25, "yellowRedCards": 0, "savesCaught": 0,
    "savesParried": 0, "totalOwnHalfPasses": 188, "totalOppositionHalfPasses": 272, "totwAppearances": 0, "expectedGoals": 3.7872,
    "goalKicks": 0, "ballRecovery": 82, "appearances": 25
    },
    {
    "Name": "Will Vaulks", "Position": "DM", "rating": 6.775, "goals": 0, "bigChancesCreated": 3, "bigChancesMissed": 0,
    "assists": 0, "goalsAssistsSum": 0, "accuratePasses": 695, "inaccuratePasses": 213, "totalPasses": 908,
    "accuratePassesPercentage": 76.541850220264, "accurateOwnHalfPasses": 442, "accurateOppositionHalfPasses": 265,
    "accurateFinalThirdPasses": 117, "keyPasses": 18, "successfulDribbles": 7, "successfulDribblesPercentage": 87.5,
    "tackles": 42, "interceptions": 20, "yellowCards": 2, "directRedCards": 0, "redCards": 0, "accurateCrosses": 12,
    "accurateCrossesPercentage": 21.428571428571, "totalShots": 12, "shotsOnTarget": 3, "shotsOffTarget": 3,
    "groundDuelsWon": 58, "groundDuelsWonPercentage": 51.785714285714, "aerialDuelsWon": 40, "aerialDuelsWonPercentage": 71.428571428571,
    "totalDuelsWon": 98, "totalDuelsWonPercentage": 58.333333333333, "minutesPlayed": 1704, "goalConversionPercentage": 0,
    "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 1, "shotFromSetPiece": 2, "freeKickGoal": 0,
    "goalsFromInsideTheBox": 0, "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 1, "shotsFromOutsideTheBox": 11,
    "headedGoals": 0, "leftFootGoals": 0, "rightFootGoals": 0, "accurateLongBalls": 72, "accurateLongBallsPercentage": 43.11377245509,
    "clearances": 46, "errorLeadToGoal": 3, "errorLeadToShot": 1, "dispossessed": 10, "possessionLost": 302,
    "possessionWonAttThird": 4, "totalChippedPasses": 96, "accurateChippedPasses": 41, "touches": 1220, "wasFouled": 10,
    "fouls": 16, "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 29, "offsides": 0, "blockedShots": 6, "passToAssist": 1,
    "saves": 0, "cleanSheet": 5, "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0, "savedShotsFromOutsideTheBox": 0,
    "goalsConcededInsideTheBox": 30, "goalsConcededOutsideTheBox": 1, "punches": 0, "runsOut": 0, "successfulRunsOut": 0,
    "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 19, "penaltyConversion": 0, "setPieceConversion": 0,
    "totalAttemptAssist": 17, "totalContest": 8, "totalCross": 56, "duelLost": 70, "aerialLost": 16, "attemptPenaltyMiss": 0,
    "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0, "totalLongBalls": 167, "goalsConceded": 31, "tacklesWon": 28,
    "tacklesWonPercentage": 66.666666666667, "scoringFrequency": 0, "yellowRedCards": 0, "savesCaught": 0,
    "savesParried": 0, "totalOwnHalfPasses": 497, "totalOppositionHalfPasses": 467, "totwAppearances": 0, "expectedGoals": 0.47,
    "goalKicks": 0, "ballRecovery": 99, "appearances": 24
    },
    {
    "Name": "Matt Phillips", "Position": "RW", "rating": 6.5666666666667, "goals": 0, "bigChancesCreated": 1,
    "bigChancesMissed": 0, "assists": 1, "goalsAssistsSum": 1, "accuratePasses": 105, "inaccuratePasses": 36,
    "totalPasses": 141, "accuratePassesPercentage": 74.468085106383, "accurateOwnHalfPasses": 43,
    "accurateOppositionHalfPasses": 65, "accurateFinalThirdPasses": 31, "keyPasses": 6, "successfulDribbles": 4,
    "successfulDribblesPercentage": 40, "tackles": 4, "interceptions": 3, "yellowCards": 0, "directRedCards": 0,
    "redCards": 0, "accurateCrosses": 3, "accurateCrossesPercentage": 27.272727272727, "totalShots": 4,
    "shotsOnTarget": 2, "shotsOffTarget": 0, "groundDuelsWon": 18, "groundDuelsWonPercentage": 45,
    "aerialDuelsWon": 13, "aerialDuelsWonPercentage": 41.935483870968, "totalDuelsWon": 31, "totalDuelsWonPercentage": 43.661971830986,
    "minutesPlayed": 461, "goalConversionPercentage": 0, "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0,
    "penaltyConceded": 0, "shotFromSetPiece": 0, "freeKickGoal": 0, "goalsFromInsideTheBox": 0,
    "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 3, "shotsFromOutsideTheBox": 1, "headedGoals": 0,
    "leftFootGoals": 0, "rightFootGoals": 0, "accurateLongBalls": 3, "accurateLongBallsPercentage": 27.272727272727,
    "clearances": 5, "errorLeadToGoal": 0, "errorLeadToShot": 0, "dispossessed": 3, "possessionLost": 76,
    "possessionWonAttThird": 2, "totalChippedPasses": 7, "accurateChippedPasses": 4, "touches": 231, "wasFouled": 10,
    "fouls": 8, "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 6, "offsides": 0, "blockedShots": 2, "passToAssist": 0,
    "saves": 0, "cleanSheet": 0, "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0,
    "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 8, "goalsConcededOutsideTheBox": 2, "punches": 0,
    "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 5,
    "penaltyConversion": 0, "setPieceConversion": 0, "totalAttemptAssist": 6, "totalContest": 10, "totalCross": 11,
    "duelLost": 40, "aerialLost": 18, "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0,
    "totalLongBalls": 11, "goalsConceded": 10, "tacklesWon": 2, "tacklesWonPercentage": 50, "scoringFrequency": 0,
    "yellowRedCards": 0, "savesCaught": 0, "savesParried": 0, "totalOwnHalfPasses": 48, "totalOppositionHalfPasses": 104,
    "totwAppearances": 0, "expectedGoals": 0.2388, "goalKicks": 0, "ballRecovery": 23, "appearances": 12
    },
    {
    "Name": "Kyle Edwards", "Position": "LW", "rating": 6.7571428571429, "goals": 0, "bigChancesCreated": 2, "bigChancesMissed": 0,
    "assists": 1, "goalsAssistsSum": 1, "accuratePasses": 52, "inaccuratePasses": 10, "totalPasses": 62, "accuratePassesPercentage": 83.870967741935,
    "accurateOwnHalfPasses": 18, "accurateOppositionHalfPasses": 36, "accurateFinalThirdPasses": 21, "keyPasses": 4, "successfulDribbles": 2,
    "successfulDribblesPercentage": 33.333333333333, "tackles": 2, "interceptions": 2, "yellowCards": 0, "directRedCards": 0, "redCards": 0,
    "accurateCrosses": 2, "accurateCrossesPercentage": 25, "totalShots": 1, "shotsOnTarget": 0, "shotsOffTarget": 0, "groundDuelsWon": 9,
    "groundDuelsWonPercentage": 52.941176470588, "aerialDuelsWon": 3, "aerialDuelsWonPercentage": 50, "totalDuelsWon": 12, "totalDuelsWonPercentage": 52.173913043478,
    "minutesPlayed": 196, "goalConversionPercentage": 0, "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 0,
    "shotFromSetPiece": 0, "freeKickGoal": 0, "goalsFromInsideTheBox": 0, "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 1, "shotsFromOutsideTheBox": 0,
    "headedGoals": 0, "leftFootGoals": 0, "rightFootGoals": 0, "accurateLongBalls": 1, "accurateLongBallsPercentage": 25, "clearances": 3, "errorLeadToGoal": 0,
    "errorLeadToShot": 0, "dispossessed": 3, "possessionLost": 30, "possessionWonAttThird": 1, "totalChippedPasses": 2, "accurateChippedPasses": 1,
    "touches": 110, "wasFouled": 5, "fouls": 0, "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 1, "offsides": 0, "blockedShots": 1, "passToAssist": 0,
    "saves": 0, "cleanSheet": 0, "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0, "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 2,
    "goalsConcededOutsideTheBox": 1, "punches": 0, "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 1,
    "penaltyConversion": 0, "setPieceConversion": 0, "totalAttemptAssist": 4, "totalContest": 6, "totalCross": 8, "duelLost": 11, "aerialLost": 3, "attemptPenaltyMiss": 0,
    "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0, "totalLongBalls": 4, "goalsConceded": 3, "tacklesWon": 1, "tacklesWonPercentage": 50, "scoringFrequency": 0,
    "yellowRedCards": 0, "savesCaught": 0, "savesParried": 0, "totalOwnHalfPasses": 19, "totalOppositionHalfPasses": 51, "totwAppearances": 0, "expectedGoals": 0.0382,
    "goalKicks": 0, "ballRecovery": 14, "appearances": 7
    },
    {
    "Name": "Owen Dale", "Position": "RW", "rating": 6.5909090909091, "goals": 0, "bigChancesCreated": 1, "bigChancesMissed": 1, "assists": 0,
    "goalsAssistsSum": 0, "accuratePasses": 76, "inaccuratePasses": 21, "totalPasses": 97, "accuratePassesPercentage": 78.350515463918,
    "accurateOwnHalfPasses": 28, "accurateOppositionHalfPasses": 49, "accurateFinalThirdPasses": 34, "keyPasses": 5, "successfulDribbles": 2,
    "successfulDribblesPercentage": 28.571428571429, "tackles": 5, "interceptions": 4, "yellowCards": 0, "directRedCards": 0, "redCards": 0,
    "accurateCrosses": 1, "accurateCrossesPercentage": 14.285714285714, "totalShots": 6, "shotsOnTarget": 1, "shotsOffTarget": 1, "groundDuelsWon": 11,
    "groundDuelsWonPercentage": 33.333333333333, "aerialDuelsWon": 2, "aerialDuelsWonPercentage": 18.181818181818, "totalDuelsWon": 13, "totalDuelsWonPercentage": 29.545454545455,
    "minutesPlayed": 364, "goalConversionPercentage": 0, "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 0, "shotFromSetPiece": 0,
    "freeKickGoal": 0, "goalsFromInsideTheBox": 0, "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 3, "shotsFromOutsideTheBox": 3, "headedGoals": 0,
    "leftFootGoals": 0, "rightFootGoals": 0, "accurateLongBalls": 8, "accurateLongBallsPercentage": 57.142857142857, "clearances": 3, "errorLeadToGoal": 0,
    "errorLeadToShot": 0, "dispossessed": 7, "possessionLost": 48, "possessionWonAttThird": 3, "totalChippedPasses": 9, "accurateChippedPasses": 7, "touches": 169,
    "wasFouled": 4, "fouls": 8, "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 2, "offsides": 1, "blockedShots": 4, "passToAssist": 0, "saves": 0, "cleanSheet": 0,
    "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0, "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 9, "goalsConcededOutsideTheBox": 1,
    "punches": 0, "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 4, "penaltyConversion": 0, "setPieceConversion": 0,
    "totalAttemptAssist": 5, "totalContest": 7, "totalCross": 7, "duelLost": 31, "aerialLost": 9, "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0,
    "totalLongBalls": 14, "goalsConceded": 10, "tacklesWon": 5, "tacklesWonPercentage": 100, "scoringFrequency": 0, "yellowRedCards": 0, "savesCaught": 0,
    "savesParried": 0, "totalOwnHalfPasses": 34, "totalOppositionHalfPasses": 70, "totwAppearances": 0, "expectedGoals": 0.4674, "goalKicks": 0, "ballRecovery": 17,
    "appearances": 11
    },
    {
    "Name": "Josh McEachran", "Position": "CM", "rating": 6.8, "goals": 0, "bigChancesCreated": 3, "bigChancesMissed": 0, "assists": 1,
    "goalsAssistsSum": 1, "accuratePasses": 228, "inaccuratePasses": 26, "totalPasses": 254, "accuratePassesPercentage": 89.763779527559,
    "accurateOwnHalfPasses": 158, "accurateOppositionHalfPasses": 74, "accurateFinalThirdPasses": 20, "keyPasses": 8, "successfulDribbles": 5,
    "successfulDribblesPercentage": 55.555555555556, "tackles": 17, "interceptions": 7, "yellowCards": 1, "directRedCards": 0, "redCards": 0,
    "accurateCrosses": 4, "accurateCrossesPercentage": 28.571428571429, "totalShots": 1, "shotsOnTarget": 0, "shotsOffTarget": 0, "groundDuelsWon": 24,
    "groundDuelsWonPercentage": 61.538461538462, "aerialDuelsWon": 4, "aerialDuelsWonPercentage": 44.444444444444, "totalDuelsWon": 28, "totalDuelsWonPercentage": 58.333333333333,
    "minutesPlayed": 509, "goalConversionPercentage": 0, "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 0,
    "shotFromSetPiece": 1, "freeKickGoal": 0, "goalsFromInsideTheBox": 0, "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 0, "shotsFromOutsideTheBox": 1,
    "headedGoals": 0, "leftFootGoals": 0, "rightFootGoals": 0, "accurateLongBalls": 13, "accurateLongBallsPercentage": 54.166666666667, "clearances": 7, "errorLeadToGoal": 0,
    "errorLeadToShot": 0, "dispossessed": 5, "possessionLost": 47, "possessionWonAttThird": 0, "totalChippedPasses": 14, "accurateChippedPasses": 8, "touches": 337,
    "wasFouled": 3, "fouls": 4, "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 2, "offsides": 0, "blockedShots": 1, "passToAssist": 0, "saves": 0, "cleanSheet": 1,
    "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0, "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 3, "goalsConcededOutsideTheBox": 2,
    "punches": 0, "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 6, "penaltyConversion": 0, "setPieceConversion": 0,
    "totalAttemptAssist": 8, "totalContest": 9, "totalCross": 14, "duelLost": 20, "aerialLost": 5, "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0,
    "totalLongBalls": 24, "goalsConceded": 5, "tacklesWon": 8, "tacklesWonPercentage": 47.058823529412, "scoringFrequency": 0, "yellowRedCards": 0, "savesCaught": 0,
    "savesParried": 0, "totalOwnHalfPasses": 159, "totalOppositionHalfPasses": 109, "totwAppearances": 1, "expectedGoals": 0.0519, "goalKicks": 0, "ballRecovery": 30,
    "appearances": 12
    },
    {
    "Name": "Idris El Mizouni", "Position": "CM", "rating": 6.6909090909091, "goals": 1, "bigChancesCreated": 1, "bigChancesMissed": 3, "assists": 2,
    "goalsAssistsSum": 3, "accuratePasses": 456, "inaccuratePasses": 80, "totalPasses": 536, "accuratePassesPercentage": 85.074626865672, "accurateOwnHalfPasses": 227,
    "accurateOppositionHalfPasses": 231, "accurateFinalThirdPasses": 106, "keyPasses": 13, "successfulDribbles": 8, "successfulDribblesPercentage": 38.095238095238, 
    "tackles": 43, "interceptions": 13, "yellowCards": 2, "directRedCards": 0, "redCards": 0, "accurateCrosses": 2, "accurateCrossesPercentage": 33.333333333333, 
    "totalShots": 17, "shotsOnTarget": 6, "shotsOffTarget": 6, "groundDuelsWon": 58, "groundDuelsWonPercentage": 52.252252252252, "aerialDuelsWon": 8, "aerialDuelsWonPercentage": 32,
    "totalDuelsWon": 66, "totalDuelsWonPercentage": 48.529411764706, "minutesPlayed": 1210, "goalConversionPercentage": 5.8823529411765, "penaltiesTaken": 0, "penaltyGoals": 0, 
    "penaltyWon": 0, "penaltyConceded": 0, "shotFromSetPiece": 0, "freeKickGoal": 0, "goalsFromInsideTheBox": 1, "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 8, 
    "shotsFromOutsideTheBox": 9, "headedGoals": 0, "leftFootGoals": 1, "rightFootGoals": 0, "accurateLongBalls": 10, "accurateLongBallsPercentage": 45.454545454545, "clearances": 14,
    "errorLeadToGoal": 0, "errorLeadToShot": 1, "dispossessed": 8, "possessionLost": 122, "possessionWonAttThird": 5, "totalChippedPasses": 17, "accurateChippedPasses": 10, 
    "touches": 725, "wasFouled": 7, "fouls": 16, "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 19, "offsides": 1, "blockedShots": 5, "passToAssist": 0, "saves": 0, "cleanSheet": 2, 
    "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0, "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 13, "goalsConcededOutsideTheBox": 5, 
    "punches": 0, "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 12, "penaltyConversion": 0, "setPieceConversion": 0, 
    "totalAttemptAssist": 13, "totalContest": 21, "totalCross": 6, "duelLost": 70, "aerialLost": 17, "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0, 
    "totalLongBalls": 22, "goalsConceded": 18, "tacklesWon": 22, "tacklesWonPercentage": 51.162790697674, "scoringFrequency": 1210, "yellowRedCards": 0, "savesCaught": 0, 
    "savesParried": 0, "totalOwnHalfPasses": 261, "totalOppositionHalfPasses": 281, "totwAppearances": 0, "goalKicks": 0, "ballRecovery": 64, "appearances": 22
    },
    {
    "Name": "Peter Kioso", "Position": "RB", "rating": 6.8833333333333, "goals": 0, "bigChancesCreated": 1, "bigChancesMissed": 1, "assists": 1,
    "goalsAssistsSum": 1, "accuratePasses": 443, "inaccuratePasses": 138, "totalPasses": 581, "accuratePassesPercentage": 76.247848537005,
    "accurateOwnHalfPasses": 251, "accurateOppositionHalfPasses": 196, "accurateFinalThirdPasses": 75, "keyPasses": 5, "successfulDribbles": 5,
    "successfulDribblesPercentage": 62.5, "tackles": 38, "interceptions": 20, "yellowCards": 4, "directRedCards": 0, "redCards": 0, "accurateCrosses": 4,
    "accurateCrossesPercentage": 20, "totalShots": 6, "shotsOnTarget": 0, "shotsOffTarget": 4, "groundDuelsWon": 75, "groundDuelsWonPercentage": 64.655172413793,
    "aerialDuelsWon": 28, "aerialDuelsWonPercentage": 58.333333333333, "totalDuelsWon": 103, "totalDuelsWonPercentage": 62.80487804878, "minutesPlayed": 1419,
    "goalConversionPercentage": 0, "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 0, "shotFromSetPiece": 0, "freeKickGoal": 0,
    "goalsFromInsideTheBox": 0, "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 4, "shotsFromOutsideTheBox": 2, "headedGoals": 0, "leftFootGoals": 0,
    "rightFootGoals": 0, "accurateLongBalls": 28, "accurateLongBallsPercentage": 36.842105263158, "clearances": 40, "errorLeadToGoal": 1, "errorLeadToShot": 1,
    "dispossessed": 8, "possessionLost": 226, "possessionWonAttThird": 0, "totalChippedPasses": 35, "accurateChippedPasses": 14, "touches": 981, "wasFouled": 34,
    "fouls": 21, "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 10, "offsides": 0, "blockedShots": 2, "passToAssist": 0, "saves": 0, "cleanSheet": 2,
    "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0, "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 21, "goalsConcededOutsideTheBox": 3,
    "punches": 0, "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 16, "penaltyConversion": 0, "setPieceConversion": 0,
    "totalAttemptAssist": 5, "totalContest": 8, "totalCross": 20, "duelLost": 61, "aerialLost": 20, "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0,
    "totalLongBalls": 76, "goalsConceded": 24, "tacklesWon": 21, "tacklesWonPercentage": 55.263157894737, "scoringFrequency": 0, "yellowRedCards": 0, "savesCaught": 0,
    "savesParried": 0, "totalOwnHalfPasses": 293, "totalOppositionHalfPasses": 308, "totwAppearances": 0, "expectedGoals": 0.5646, "goalKicks": 0, "ballRecovery": 37,
    "appearances": 18
    },
    {
    "Name": "Elliott Moore", "Position": "CB", "rating": 6.925, "goals": 0, "bigChancesCreated": 2, "bigChancesMissed": 1, "assists": 2,
    "goalsAssistsSum": 2, "accuratePasses": 761, "inaccuratePasses": 93, "totalPasses": 854, "accuratePassesPercentage": 89.110070257611,
    "accurateOwnHalfPasses": 643, "accurateOppositionHalfPasses": 118, "accurateFinalThirdPasses": 17, "keyPasses": 2, "successfulDribbles": 2,
    "successfulDribblesPercentage": 66.666666666667, "tackles": 16, "interceptions": 14, "yellowCards": 6, "directRedCards": 0, "redCards": 0,
    "accurateCrosses": 0, "accurateCrossesPercentage": 0, "totalShots": 8, "shotsOnTarget": 3, "shotsOffTarget": 4, "groundDuelsWon": 21,
    "groundDuelsWonPercentage": 55.263157894737, "aerialDuelsWon": 62, "aerialDuelsWonPercentage": 72.941176470588, "totalDuelsWon": 83, "totalDuelsWonPercentage": 67.479674796748,
    "minutesPlayed": 1717, "goalConversionPercentage": 0, "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 1, "shotFromSetPiece": 0,
    "freeKickGoal": 0, "goalsFromInsideTheBox": 0, "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 8, "shotsFromOutsideTheBox": 0, "headedGoals": 0,
    "leftFootGoals": 0, "rightFootGoals": 0, "accurateLongBalls": 38, "accurateLongBallsPercentage": 44.705882352941, "clearances": 132, "errorLeadToGoal": 0,
    "errorLeadToShot": 0, "dispossessed": 0, "possessionLost": 100, "possessionWonAttThird": 0, "totalChippedPasses": 28, "accurateChippedPasses": 13, "touches": 1076,
    "wasFouled": 3, "fouls": 14, "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 2, "offsides": 0, "blockedShots": 1, "passToAssist": 0, "saves": 0, "cleanSheet": 5,
    "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0, "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 27, "goalsConcededOutsideTheBox": 3,
    "punches": 0, "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 20, "penaltyConversion": 0, "setPieceConversion": 0,
    "totalAttemptAssist": 2, "totalContest": 3, "totalCross": 0, "duelLost": 40, "aerialLost": 23, "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0,
    "totalLongBalls": 85, "goalsConceded": 30, "tacklesWon": 8, "tacklesWonPercentage": 50, "scoringFrequency": 0, "yellowRedCards": 0, "savesCaught": 0,
    "savesParried": 0, "totalOwnHalfPasses": 678, "totalOppositionHalfPasses": 176, "totwAppearances": 0, "expectedGoals": 0.3443, "goalKicks": 42, "ballRecovery": 44,
    "appearances": 20
    },
    {
    "Name": "Joe Bennett", "Position": "LB", "rating": 6.675, "goals": 0, "bigChancesCreated": 0, "bigChancesMissed": 0, "assists": 0,
    "goalsAssistsSum": 0, "accuratePasses": 132, "inaccuratePasses": 34, "totalPasses": 166, "accuratePassesPercentage": 79.518072289157,
    "accurateOwnHalfPasses": 101, "accurateOppositionHalfPasses": 31, "accurateFinalThirdPasses": 14, "keyPasses": 0, "successfulDribbles": 1,
    "successfulDribblesPercentage": 100, "tackles": 9, "interceptions": 2, "yellowCards": 0, "directRedCards": 0, "redCards": 0,
    "accurateCrosses": 0, "accurateCrossesPercentage": 0, "totalShots": 0, "shotsOnTarget": 0, "shotsOffTarget": 0, "groundDuelsWon": 14,
    "groundDuelsWonPercentage": 82.352941176471, "aerialDuelsWon": 5, "aerialDuelsWonPercentage": 62.5, "totalDuelsWon": 19, "totalDuelsWonPercentage": 76,
    "minutesPlayed": 315, "goalConversionPercentage": 0, "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 0,
    "shotFromSetPiece": 0, "freeKickGoal": 0, "goalsFromInsideTheBox": 0, "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 0, "shotsFromOutsideTheBox": 0,
    "headedGoals": 0, "leftFootGoals": 0, "rightFootGoals": 0, "accurateLongBalls": 5, "accurateLongBallsPercentage": 23.809523809524, "clearances": 9, "errorLeadToGoal": 0,
    "errorLeadToShot": 1, "dispossessed": 1, "possessionLost": 44, "possessionWonAttThird": 2, "totalChippedPasses": 6, "accurateChippedPasses": 1, "touches": 236,
    "wasFouled": 5, "fouls": 2, "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 0, "offsides": 0, "blockedShots": 0, "passToAssist": 0, "saves": 0, "cleanSheet": 1,
    "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0, "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 6, "goalsConcededOutsideTheBox": 0,
    "punches": 0, "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 4, "penaltyConversion": 0, "setPieceConversion": 0,
    "totalAttemptAssist": 0, "totalContest": 1, "totalCross": 0, "duelLost": 6, "aerialLost": 3, "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0,
    "totalLongBalls": 21, "goalsConceded": 6, "tacklesWon": 4, "tacklesWonPercentage": 44.444444444444, "scoringFrequency": 0, "yellowRedCards": 0, "savesCaught": 0,
    "savesParried": 0, "totalOwnHalfPasses": 113, "totalOppositionHalfPasses": 53, "totwAppearances": 0, "goalKicks": 0, "ballRecovery": 18, "appearances": 4
    },
    {
    "Name": "Sam Long", "Position": "RB", "rating": 6.9, "goals": 0, "bigChancesCreated": 1, "bigChancesMissed": 0, "assists": 1,
    "goalsAssistsSum": 1, "accuratePasses": 423, "inaccuratePasses": 137, "totalPasses": 560, "accuratePassesPercentage": 75.535714285714,
    "accurateOwnHalfPasses": 300, "accurateOppositionHalfPasses": 126, "accurateFinalThirdPasses": 51, "keyPasses": 9, "successfulDribbles": 0,
    "successfulDribblesPercentage": 0, "tackles": 21, "interceptions": 23, "yellowCards": 1, "directRedCards": 0, "redCards": 0,
    "accurateCrosses": 3, "accurateCrossesPercentage": 33.333333333333, "totalShots": 6, "shotsOnTarget": 2, "shotsOffTarget": 2, "groundDuelsWon": 31,
    "groundDuelsWonPercentage": 63.265306122449, "aerialDuelsWon": 41, "aerialDuelsWonPercentage": 57.746478873239, "totalDuelsWon": 72, "totalDuelsWonPercentage": 60,
    "minutesPlayed": 1211, "goalConversionPercentage": 0, "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 0, "shotFromSetPiece": 0,
    "freeKickGoal": 0, "goalsFromInsideTheBox": 0, "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 5, "shotsFromOutsideTheBox": 1, "headedGoals": 0,
    "leftFootGoals": 0, "rightFootGoals": 0, "accurateLongBalls": 22, "accurateLongBallsPercentage": 23.655913978495, "clearances": 84, "errorLeadToGoal": 0,
    "errorLeadToShot": 1, "dispossessed": 2, "possessionLost": 182, "possessionWonAttThird": 1, "totalChippedPasses": 34, "accurateChippedPasses": 13, "touches": 848,
    "wasFouled": 11, "fouls": 7, "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 6, "offsides": 2, "blockedShots": 2, "passToAssist": 0, "saves": 0, "cleanSheet": 3,
    "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0, "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 19, "goalsConcededOutsideTheBox": 2,
    "punches": 0, "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 13, "penaltyConversion": 0, "setPieceConversion": 0,
    "totalAttemptAssist": 9, "totalContest": 5, "totalCross": 9, "duelLost": 48, "aerialLost": 30, "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0,
    "totalLongBalls": 93, "goalsConceded": 21, "tacklesWon": 12, "tacklesWonPercentage": 57.142857142857, "scoringFrequency": 0, "yellowRedCards": 0, "savesCaught": 0,
    "savesParried": 0, "totalOwnHalfPasses": 335, "totalOppositionHalfPasses": 234, "totwAppearances": 0, "expectedGoals": 0.5534, "goalKicks": 3, "ballRecovery": 41,
    "appearances": 16
    },
    {
    "Name": "Jordan Thorniley", "Position": "CB", "rating": 6.7, "goals": 0, "bigChancesCreated": 0, "bigChancesMissed": 0, "assists": 0,
    "goalsAssistsSum": 0, "accuratePasses": 8, "inaccuratePasses": 3, "totalPasses": 11, "accuratePassesPercentage": 72.727272727273,
    "accurateOwnHalfPasses": 8, "accurateOppositionHalfPasses": 0, "accurateFinalThirdPasses": 0, "keyPasses": 0, "successfulDribbles": 0,
    "successfulDribblesPercentage": 0, "tackles": 0, "interceptions": 2, "yellowCards": 0, "directRedCards": 0, "redCards": 0, "accurateCrosses": 0,
    "accurateCrossesPercentage": 0, "totalShots": 0, "shotsOnTarget": 0, "shotsOffTarget": 0, "groundDuelsWon": 0, "groundDuelsWonPercentage": 0,
    "aerialDuelsWon": 5, "aerialDuelsWonPercentage": 100, "totalDuelsWon": 5, "totalDuelsWonPercentage": 83.333333333333, "minutesPlayed": 33, "goalConversionPercentage": 0,
    "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 0, "shotFromSetPiece": 0, "freeKickGoal": 0, "goalsFromInsideTheBox": 0,
    "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 0, "shotsFromOutsideTheBox": 0, "headedGoals": 0, "leftFootGoals": 0, "rightFootGoals": 0,
    "accurateLongBalls": 1, "accurateLongBallsPercentage": 50, "clearances": 3, "errorLeadToGoal": 0, "errorLeadToShot": 0, "dispossessed": 0,
    "possessionLost": 3, "possessionWonAttThird": 0, "totalChippedPasses": 0, "accurateChippedPasses": 0, "touches": 18, "wasFouled": 0, "fouls": 1,
    "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 0, "offsides": 0, "blockedShots": 0, "passToAssist": 0, "saves": 0, "cleanSheet": 0, "penaltyFaced": 0,
    "penaltySave": 0, "savedShotsFromInsideTheBox": 0, "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 1, "goalsConcededOutsideTheBox": 0,
    "punches": 0, "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 0, "penaltyConversion": 0,
    "setPieceConversion": 0, "totalAttemptAssist": 0, "totalContest": 0, "totalCross": 0, "duelLost": 1, "aerialLost": 0, "attemptPenaltyMiss": 0,
    "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0, "totalLongBalls": 2, "goalsConceded": 1, "tacklesWon": 0, "tacklesWonPercentage": 0,
    "scoringFrequency": 0, "yellowRedCards": 0, "savesCaught": 0, "savesParried": 0, "totalOwnHalfPasses": 10, "totalOppositionHalfPasses": 1, "totwAppearances": 0,
    "goalKicks": 0, "ballRecovery": 0, "appearances": 1
    },
    {
    "Name": "Greg Leigh", "Position": "LB", "rating": 6.9, "goals": 3, "bigChancesCreated": 6, "bigChancesMissed": 3, "assists": 1,
    "goalsAssistsSum": 4, "accuratePasses": 410, "inaccuratePasses": 176, "totalPasses": 586, "accuratePassesPercentage": 69.965870307167,
    "accurateOwnHalfPasses": 227, "accurateOppositionHalfPasses": 192, "accurateFinalThirdPasses": 82, "keyPasses": 15, "successfulDribbles": 11,
    "successfulDribblesPercentage": 68.75, "tackles": 25, "interceptions": 26, "yellowCards": 0, "directRedCards": 0, "redCards": 0,
    "accurateCrosses": 9, "accurateCrossesPercentage": 29.032258064516, "totalShots": 9, "shotsOnTarget": 4, "shotsOffTarget": 4, "groundDuelsWon": 45,
    "groundDuelsWonPercentage": 69.230769230769, "aerialDuelsWon": 48, "aerialDuelsWonPercentage": 62.337662337662, "totalDuelsWon": 93, "totalDuelsWonPercentage": 65.492957746479,
    "minutesPlayed": 1436, "goalConversionPercentage": 33.333333333333, "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 0, "shotFromSetPiece": 0,
    "freeKickGoal": 0, "goalsFromInsideTheBox": 3, "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 7, "shotsFromOutsideTheBox": 2, "headedGoals": 0,
    "leftFootGoals": 1, "rightFootGoals": 2, "accurateLongBalls": 19, "accurateLongBallsPercentage": 24.358974358974, "clearances": 45, "errorLeadToGoal": 0,
    "errorLeadToShot": 0, "dispossessed": 6, "possessionLost": 262, "possessionWonAttThird": 1, "totalChippedPasses": 41, "accurateChippedPasses": 10, "touches": 962,
    "wasFouled": 10, "fouls": 3, "hitWoodwork": 1, "ownGoals": 0, "dribbledPast": 7, "offsides": 1, "blockedShots": 1, "passToAssist": 0, "saves": 0, "cleanSheet": 4,
    "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0, "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 24, "goalsConcededOutsideTheBox": 4,
    "punches": 0, "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 14, "penaltyConversion": 0, "setPieceConversion": 0,
    "totalAttemptAssist": 15, "totalContest": 16, "totalCross": 31, "duelLost": 49, "aerialLost": 29, "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0,
    "totalLongBalls": 78, "goalsConceded": 28, "tacklesWon": 14, "tacklesWonPercentage": 56, "scoringFrequency": 478.66666666667, "yellowRedCards": 0, "savesCaught": 0,
    "savesParried": 0, "totalOwnHalfPasses": 289, "totalOppositionHalfPasses": 328, "totwAppearances": 0, "expectedGoals": 2.2354, "goalKicks": 0, "ballRecovery": 65,
    "appearances": 21
    },
    {
    "Name": "Ben Nelson", "Position": "CB", "rating": 6.825, "goals": 0, "bigChancesCreated": 0, "bigChancesMissed": 0, "assists": 0,
    "goalsAssistsSum": 0, "accuratePasses": 307, "inaccuratePasses": 76, "totalPasses": 383, "accuratePassesPercentage": 80.156657963446,
    "accurateOwnHalfPasses": 250, "accurateOppositionHalfPasses": 57, "accurateFinalThirdPasses": 13, "keyPasses": 1, "successfulDribbles": 2,
    "successfulDribblesPercentage": 100, "tackles": 11, "interceptions": 6, "yellowCards": 1, "directRedCards": 0, "redCards": 0,
    "accurateCrosses": 0, "accurateCrossesPercentage": 0, "totalShots": 0, "shotsOnTarget": 0, "shotsOffTarget": 0, "groundDuelsWon": 18,
    "groundDuelsWonPercentage": 64.285714285714, "aerialDuelsWon": 17, "aerialDuelsWonPercentage": 62.962962962963, "totalDuelsWon": 35, "totalDuelsWonPercentage": 63.636363636364,
    "minutesPlayed": 647, "goalConversionPercentage": 0, "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 0,
    "shotFromSetPiece": 0, "freeKickGoal": 0, "goalsFromInsideTheBox": 0, "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 0, "shotsFromOutsideTheBox": 0,
    "headedGoals": 0, "leftFootGoals": 0, "rightFootGoals": 0, "accurateLongBalls": 31, "accurateLongBallsPercentage": 43.661971830986, "clearances": 41, "errorLeadToGoal": 0,
    "errorLeadToShot": 0, "dispossessed": 1, "possessionLost": 80, "possessionWonAttThird": 0, "totalChippedPasses": 26, "accurateChippedPasses": 10, "touches": 470,
    "wasFouled": 5, "fouls": 7, "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 2, "offsides": 0, "blockedShots": 0, "passToAssist": 0, "saves": 0, "cleanSheet": 1,
    "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0, "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 7, "goalsConcededOutsideTheBox": 1,
    "punches": 0, "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 8, "penaltyConversion": 0, "setPieceConversion": 0,
    "totalAttemptAssist": 1, "totalContest": 2, "totalCross": 0, "duelLost": 20, "aerialLost": 10, "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0,
    "totalLongBalls": 71, "goalsConceded": 8, "tacklesWon": 7, "tacklesWonPercentage": 63.636363636364, "scoringFrequency": 0, "yellowRedCards": 0, "savesCaught": 0,
    "savesParried": 0, "totalOwnHalfPasses": 279, "totalOppositionHalfPasses": 104, "totwAppearances": 0, "goalKicks": 14, "ballRecovery": 24, "appearances": 8
    },
    {
    "Name": "Hidde ter Avest", "Position": "RB", "rating": 6.6875, "goals": 1, "bigChancesCreated": 0, "bigChancesMissed": 2, "assists": 0,
    "goalsAssistsSum": 1, "accuratePasses": 91, "inaccuratePasses": 31, "totalPasses": 122, "accuratePassesPercentage": 74.590163934426,
    "accurateOwnHalfPasses": 44, "accurateOppositionHalfPasses": 47, "accurateFinalThirdPasses": 19, "keyPasses": 2, "successfulDribbles": 2,
    "successfulDribblesPercentage": 40, "tackles": 4, "interceptions": 10, "yellowCards": 0, "directRedCards": 0, "redCards": 0,
    "accurateCrosses": 0, "accurateCrossesPercentage": 0, "totalShots": 5, "shotsOnTarget": 4, "shotsOffTarget": 0, "groundDuelsWon": 9,
    "groundDuelsWonPercentage": 40.909090909091, "aerialDuelsWon": 6, "aerialDuelsWonPercentage": 54.545454545455, "totalDuelsWon": 15, "totalDuelsWonPercentage": 45.454545454545,
    "minutesPlayed": 350, "goalConversionPercentage": 20, "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 0,
    "shotFromSetPiece": 0, "freeKickGoal": 0, "goalsFromInsideTheBox": 1, "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 4, "shotsFromOutsideTheBox": 1,
    "headedGoals": 0, "leftFootGoals": 0, "rightFootGoals": 1, "accurateLongBalls": 1, "accurateLongBallsPercentage": 8.3333333333333, "clearances": 12, "errorLeadToGoal": 0,
    "errorLeadToShot": 0, "dispossessed": 2, "possessionLost": 53, "possessionWonAttThird": 0, "totalChippedPasses": 7, "accurateChippedPasses": 3, "touches": 210,
    "wasFouled": 3, "fouls": 4, "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 4, "offsides": 1, "blockedShots": 1, "passToAssist": 0, "saves": 0, "cleanSheet": 0,
    "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0, "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 8, "goalsConcededOutsideTheBox": 2,
    "punches": 0, "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 3, "penaltyConversion": 0, "setPieceConversion": 0,
    "totalAttemptAssist": 2, "totalContest": 5, "totalCross": 8, "duelLost": 18, "aerialLost": 5, "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0,
    "totalLongBalls": 12, "goalsConceded": 10, "tacklesWon": 1, "tacklesWonPercentage": 25, "scoringFrequency": 350, "yellowRedCards": 0, "savesCaught": 0,
    "savesParried": 0, "totalOwnHalfPasses": 60, "totalOppositionHalfPasses": 70, "totwAppearances": 0, "expectedGoals": 0.7571, "goalKicks": 0, "ballRecovery": 15,
    "appearances": 8
    },
    {
    "Name": "Ciaron Brown", "Position": "CB", "rating": 7.00, "goals": 3, "bigChancesCreated": 1, "bigChancesMissed": 1, "assists": 3,
    "goalsAssistsSum": 6, "accuratePasses": 933, "inaccuratePasses": 245, "totalPasses": 1178, "accuratePassesPercentage": 79.202037351443,
    "accurateOwnHalfPasses": 690, "accurateOppositionHalfPasses": 245, "accurateFinalThirdPasses": 85, "keyPasses": 6, "successfulDribbles": 8,
    "successfulDribblesPercentage": 72.727272727273, "tackles": 20, "interceptions": 37, "yellowCards": 2, "directRedCards": 0, "redCards": 0,
    "accurateCrosses": 2, "accurateCrossesPercentage": 33.333333333333, "totalShots": 14, "shotsOnTarget": 4, "shotsOffTarget": 7, "groundDuelsWon": 48,
    "groundDuelsWonPercentage": 68.571428571429, "aerialDuelsWon": 81, "aerialDuelsWonPercentage": 69.827586206897, "totalDuelsWon": 129, "totalDuelsWonPercentage": 69.354838709677,
    "minutesPlayed": 2250, "goalConversionPercentage": 21.428571428571, "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 0,
    "shotFromSetPiece": 0, "freeKickGoal": 0, "goalsFromInsideTheBox": 3, "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 13, "shotsFromOutsideTheBox": 1,
    "headedGoals": 2, "leftFootGoals": 1, "rightFootGoals": 0, "accurateLongBalls": 49, "accurateLongBallsPercentage": 28, "clearances": 131, "errorLeadToGoal": 0,
    "errorLeadToShot": 0, "dispossessed": 4, "possessionLost": 294, "possessionWonAttThird": 1, "totalChippedPasses": 90, "accurateChippedPasses": 33, "touches": 1588,
    "wasFouled": 21, "fouls": 9, "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 6, "offsides": 0, "blockedShots": 3, "passToAssist": 0, "saves": 0, "cleanSheet": 6,
    "penaltyFaced": 0, "penaltySave": 0, "savedShotsFromInsideTheBox": 0, "savedShotsFromOutsideTheBox": 0, "goalsConcededInsideTheBox": 35, "goalsConcededOutsideTheBox": 5,
    "punches": 0, "runsOut": 0, "successfulRunsOut": 0, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 25, "penaltyConversion": 0, "setPieceConversion": 0,
    "totalAttemptAssist": 6, "totalContest": 11, "totalCross": 6, "duelLost": 57, "aerialLost": 35, "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0,
    "totalLongBalls": 175, "goalsConceded": 40, "tacklesWon": 15, "tacklesWonPercentage": 75, "scoringFrequency": 750, "yellowRedCards": 0, "savesCaught": 0,
    "savesParried": 0, "totalOwnHalfPasses": 760, "totalOppositionHalfPasses": 424, "totwAppearances": 2, "expectedGoals": 1.2946, "goalKicks": 12, "ballRecovery": 79,
    "appearances": 25
    },
    {
    "Name": "Jamie Cumming", "Position": "GK", "rating": 7.076, "goals": 0, "bigChancesCreated": 0, "bigChancesMissed": 0, "assists": 0,
    "goalsAssistsSum": 0, "accuratePasses": 621, "inaccuratePasses": 366, "totalPasses": 987, "accuratePassesPercentage": 62.917933130699,
    "accurateOwnHalfPasses": 525, "accurateOppositionHalfPasses": 96, "accurateFinalThirdPasses": 20, "keyPasses": 0, "successfulDribbles": 0,
    "successfulDribblesPercentage": 0, "tackles": 0, "interceptions": 0, "yellowCards": 1, "directRedCards": 0, "redCards": 0, "accurateCrosses": 0,
    "accurateCrossesPercentage": 0, "totalShots": 0, "shotsOnTarget": 0, "shotsOffTarget": 0, "groundDuelsWon": 3, "groundDuelsWonPercentage": 50,
    "aerialDuelsWon": 5, "aerialDuelsWonPercentage": 100, "totalDuelsWon": 8, "totalDuelsWonPercentage": 72.727272727273, "minutesPlayed": 2250,
    "goalConversionPercentage": 0, "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 0, "shotFromSetPiece": 0, "freeKickGoal": 0,
    "goalsFromInsideTheBox": 0, "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 0, "shotsFromOutsideTheBox": 0, "headedGoals": 0, "leftFootGoals": 0,
    "rightFootGoals": 0, "accurateLongBalls": 222, "accurateLongBallsPercentage": 38.144329896907, "clearances": 28, "errorLeadToGoal": 1, "errorLeadToShot": 0,
    "dispossessed": 0, "possessionLost": 374, "possessionWonAttThird": 0, "totalChippedPasses": 155, "accurateChippedPasses": 109, "touches": 1248,
    "wasFouled": 5, "fouls": 1, "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 2, "offsides": 0, "blockedShots": 0, "passToAssist": 0, "saves": 87,
    "goalsPrevented": 5.5115, "cleanSheet": 6, "penaltyFaced": 3, "penaltySave": 1, "savedShotsFromInsideTheBox": 58, "savedShotsFromOutsideTheBox": 27,
    "goalsConcededInsideTheBox": 35, "goalsConcededOutsideTheBox": 5, "punches": 6, "runsOut": 20, "successfulRunsOut": 20, "highClaims": 21,
    "crossesNotClaimed": 1, "matchesStarted": 25, "penaltyConversion": 0, "setPieceConversion": 0, "totalAttemptAssist": 0, "totalContest": 0, "totalCross": 0,
    "duelLost": 3, "aerialLost": 0, "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0, "totalLongBalls": 582, "goalsConceded": 40,
    "tacklesWon": 0, "tacklesWonPercentage": 0, "scoringFrequency": 0, "yellowRedCards": 0, "savesCaught": 0, "savesParried": 18, "totalOwnHalfPasses": 601,
    "totalOppositionHalfPasses": 386, "totwAppearances": 0, "goalKicks": 172, "ballRecovery": 200, "appearances": 25
    },
    {
    "Name": "Matt Ingram", "Position": "GK", "rating": 8, "goals": 0, "bigChancesCreated": 0, "bigChancesMissed": 0, "assists": 0,
    "goalsAssistsSum": 0, "accuratePasses": 76, "inaccuratePasses": 5, "totalPasses": 81, "accuratePassesPercentage": 93.827160493827,
    "accurateOwnHalfPasses": 72, "accurateOppositionHalfPasses": 4, "accurateFinalThirdPasses": 2, "keyPasses": 0, "successfulDribbles": 0,
    "successfulDribblesPercentage": 0, "tackles": 1, "interceptions": 0, "yellowCards": 0, "directRedCards": 0, "redCards": 0, "accurateCrosses": 0,
    "accurateCrossesPercentage": 0, "totalShots": 0, "shotsOnTarget": 0, "shotsOffTarget": 0, "groundDuelsWon": 1, "groundDuelsWonPercentage": 100,
    "aerialDuelsWon": 0, "aerialDuelsWonPercentage": 0, "totalDuelsWon": 1, "totalDuelsWonPercentage": 100, "minutesPlayed": 180, "goalConversionPercentage": 0,
    "penaltiesTaken": 0, "penaltyGoals": 0, "penaltyWon": 0, "penaltyConceded": 0, "shotFromSetPiece": 0, "freeKickGoal": 0, "goalsFromInsideTheBox": 0,
    "goalsFromOutsideTheBox": 0, "shotsFromInsideTheBox": 0, "shotsFromOutsideTheBox": 0, "headedGoals": 0, "leftFootGoals": 0, "rightFootGoals": 0,
    "accurateLongBalls": 14, "accurateLongBallsPercentage": 77.777777777778, "clearances": 1, "errorLeadToGoal": 0, "errorLeadToShot": 1, "dispossessed": 0,
    "possessionLost": 5, "possessionWonAttThird": 0, "totalChippedPasses": 7, "accurateChippedPasses": 7, "touches": 101, "wasFouled": 0, "fouls": 0,
    "hitWoodwork": 0, "ownGoals": 0, "dribbledPast": 0, "offsides": 0, "blockedShots": 0, "passToAssist": 0, "saves": 10, "cleanSheet": 1, "penaltyFaced": 0,
    "penaltySave": 0, "savedShotsFromInsideTheBox": 6, "savedShotsFromOutsideTheBox": 4, "goalsConcededInsideTheBox": 0, "goalsConcededOutsideTheBox": 1,
    "punches": 1, "runsOut": 1, "successfulRunsOut": 1, "highClaims": 0, "crossesNotClaimed": 0, "matchesStarted": 2, "penaltyConversion": 0, "setPieceConversion": 0,
    "totalAttemptAssist": 0, "totalContest": 0, "totalCross": 0, "duelLost": 0, "aerialLost": 0, "attemptPenaltyMiss": 0, "attemptPenaltyPost": 0, "attemptPenaltyTarget": 0,
    "totalLongBalls": 18, "goalsConceded": 1, "tacklesWon": 1, "tacklesWonPercentage": 100, "scoringFrequency": 0, "yellowRedCards": 0, "savesCaught": 0,
    "savesParried": 3, "totalOwnHalfPasses": 74, "totalOppositionHalfPasses": 7, "totwAppearances": 0, "goalKicks": 11, "ballRecovery": 13, "appearances": 2
    }
]

insert_player_stats_batch(players_data) # Inserting the data into the database


